### ISSUE TITLE
Unsupported java.net.URI

### ISSUE THREAD

**Issue by chabhishek123** [mtedone/podam#271] opened 2019-02-27 00:43 UTC

**Comment by daivanov** [comment] 2019-03-02 10:43
Hi,

  It looks like `SomeObject` class has some property of type `java.net.URI` annotated with some `javax.validation.constraints` constraint. Could you please provide example of `SomeObject` reproducing the problem?

Thanks, Daniil

**Comment by daivanov** [comment] 2019-03-06 12:20
Hi,

  Could you please provide more information on the class you are trying to instantiate?

Thanks, Daniil

**Comment by chabhishek123** [comment] 2019-03-07 06:13
Yes, I observed there is javax.validation.constraints.

Please note these are not exact objects, but the Pojo can be built on this.

import javax.validation.constraints.NotNull;


@JsonInclude(Include.NON_NULL)
@JsonPropertyOrder({"a"})
public class Foobar {
    @JsonProperty("a")
    @JsonPropertyDescription("Link form e.g abc,def & ghi ")
    @NotNull
    private LinkForm a;
}



LinkForm is an enum class with values: abc, def, ghi.

**Comment by daivanov** [comment] 2019-03-13 05:24
Sorry for a delay. Were you able to resolve the issue? The example you provided did not contain properties of java.net.URI type.

Thanks, Daniiil

**Comment by chabhishek123** [comment] 2019-03-14 18:07
Hi Daniiil,
The issue was not solved but I am trying alternatives. It can be possible to recreate this issue with validation constraint

**Comment by daivanov** [comment] 2019-03-22 08:55
But what is the constraint causing this problem?

Thanks, Daniil

**Comment by daivanov** [comment] 2019-05-09 13:00
Closing as requested information has been never provided.

**Closed by daivanov** 2019-05-09 13:00 UTC
Labels: Investigation
