### ISSUE TITLE
MaxDepth not working with multiple fields

### ISSUE THREAD

**Issue by shollander** [mtedone/podam#263] opened 2018-04-20 14:11 UTC
I have an object with the following structure:
```java
public class MyObject {
    private String name;
    private MyObject related;
    private List<MyObject> children;
}
```

The default `maxDepth` setting of `3` is too much for me, I would like the objects to recurse only once (i.e. only `related` and `children` should be populated, but `related.related` and `related.children`, and `children[*].related` and `children[*].children` should be empty. So I created a custom `DataProviderStrategy` and overrode the `getMaxDepth()` method to return `2` instead of the default `3`. As follows:
```java
public class MyDataProviderStrategy extends AbstractRandomDataProviderStrategy {
   public MyDataProviderStrategy() {
      super.setMemoization(false);
   }

  @Override
  public int getMaxDepth(Class<?> type) {
    if(MyObject.class.isAssignableFrom(type)) {
      return 2;
    } else {
      return 1;
    }
}
```

 What happened was that the `related` field was correct (only 1 level of recursion), but the `children` field was incorrect. It was always empty even at the top level.

It also seems to me that there should be an easier way to configure `maxDepth` than overriding the method. Something like `setMaxDepth(Class<?>, int)` would be helpful.

**Comment by daivanov** [comment] 2018-06-13 15:06
In Podam 7.1.1 I cannot reproduce this problem.

**Comment by shollander** [comment] 2018-07-09 16:11
I just tried it again using Podam 7.1.1, and the problem is definitely still there.
I should clarify that the `children` field is not actually empty, it is actually populated by Podam with an `ArrayList` of all `null`s. If I change the implementation of `getMaxDepth()` to read as follows:

```java
 @Override
 public int getMaxDepth(Class<?> type) {
    if(MyObject.class.isAssignableFrom(type) || ArrayList.class.isAssignableFrom(type)) {
      return 2;
    } else {
      return 1;
    }
}
```
then the `children` field gets populated correctly. But this does not appear to be correct since that will catch any `ArrayList`, not just my `List<MyObject>` field.

**Comment by daivanov** [comment] 2018-07-10 09:05
Hi,

  Could you please share a log on debug level?

Thanks, Daniil

**Comment by daivanov** [comment] 2018-08-03 22:05
As you can see test is passing successfully. I absolutely fail to see what is being reported in this issue.

> But this does not appear to be correct since that will catch any ArrayList, not just my List<MyObject> field.
I cannot really say, why this would not be correct.

**Comment by shollander** [comment] 2018-08-05 03:39
I don't see that the test is passing successfully. Did you clone the test in the repo mentioned above and execute the test through gradle (https://github.com/shollander/podam-test)? This is what I get (using the `-i` flag as mentioned above to show the assertion stackrace info):

![image](https://user-images.githubusercontent.com/4641663/43682290-9f94525e-983e-11e8-86a9-64290b80ceb6.png)

As far as the second comment:
>>But this does not appear to be correct since that will catch any ArrayList, not just my List field.

>I cannot really say, why this would not be correct.

What I meant was that while I can get it working by forcing a depth of 2 for all ArrayList objects, it is not correct in the sense that I don't want to apply the rule that generally. I really only want it to apply to the `MyObject` class (including `List<MyObject>`), but if I have a different list of some other type I don't necessarily want it to be included in the same rule.

**Comment by daivanov** [comment] 2018-08-06 11:58
If you for whatever reason want to have different instantiation of Lists, then extend AbstractTypeManufacturer for the types in question and handle it the way you like.

Thanks, Daniil

**Comment by daivanov** [comment] 2018-08-07 13:39
If else clause is removed, then loop depth is 1, meaning any children will be left as nulls. And this is exactly what is happening.

TypeManufacturer receives [AttributeMetadata](https://github.com/mtedone/podam/blob/develop/src/main/java/uk/co/jemos/podam/api/AttributeMetadata.java), which contain information about parent POJO and reference to it. This allows to do handle recursions of the POJO hierarchy in a pretty arbitrary way.

**Comment by daivanov** [comment] 2018-08-20 15:12
If you don't mind I will close this issue.

Thanks, Daniil

**Closed** 2018-08-22 19:42 UTC
Labels: Not An Issue
